kind: Model
apiVersion: v1alpha4
metadata:
  displayName: Flood Impacts (OpenCLIM)
  type: Modelling
  name: flood-impacts
  summary: Assess flood impacts using OS MasterMap
  description: Calculates maximum depths, velocity depth products and flooded perimeters of flooded buildings
spec:
  inputs:
    env:
      - name: THRESHOLD
        title: Threshold depth (m)
        desc: Minimum depth of features to include in output
        type: number
        default: 0.3
        min: 0
        max: 1

    dataslots:
      - name: MasterMap
        description: OS MasterMap buildings geopackage. Must contain a 'toid' attribute.
        default:
          - uid: 1642d68f-f4ea-494d-b3fe-f27125f11757
            versionUid: 8fadd93c-a8aa-41d2-8adb-5d615db89b3c
        path: inputs/mastermap
        required: true

      - name: UPRN
        description: Lookup between TOID and UPRN identifiers (CSV)
        default:
          - uid: d6f74a03-1983-43df-8232-d3172e38fecf
            versionUid: 9c1fbe4d-c322-465d-9c9f-6d34da30e8a6
        path: inputs/uprn
        required: false


  outputs:
      - name: outputs/buildings.csv
        type: CSV
        desc: Maximum depths & velocity depth products and flooded perimeters of flooded buildings
