kind: Model
apiVersion: v1alpha4
metadata:
  displayName: Flood Impacts (OpenCLIM)
  type: Modelling
  name: flood-impacts
  summary: Assess flood impacts using OS MasterMap
  description: Calculates area depths and line inundated distances
spec:
  inputs:
    env:
      - name: THRESHOLD
        title: Threshold depth (m)
        desc: Minimum depth of features to include in output
        type: number
        default: 0.3
        min: 0
        max: 1

    dataslots:
      - name: MasterMap
        description: OS MasterMap
        default:
          - uid: bf346708-bf48-4f24-9c4c-48f715786765
            versionUid: 252d4e7a-ea01-42e9-8d9d-6fd8e75b139b
        path: inputs/mastermap
        required: true

  outputs:
    datasets:
      - name: outputs/features.gpkg
        type: GeoPackage
        desc: Areas and line segments with depths above threshold

      - name: outputs/buildings.csv
        type: CSV
        desc: Maximum depths and velocity depth products of flooded buildings
